[theme]

base = 'dark'

# Primary accent for interactive elements
primaryColor = '#6BA5AE'

# Background color for the main content area
backgroundColor = '#151A23'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#1c2716'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"